// This file defines a serializable represenation of AST (Abstract Syntax Tree) nodes for GEL.
// Protobuf definitions in this file should be used by GEL parsers, interpeters, and code generators.
syntax = "proto3";

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

package org.wanderlinks.gel;

option cc_enable_arenas = true;
option go_package = "github.com/miksonov/gel-parser-go/org/wanderlinks/gel/v1pb";
option java_multiple_files = true;
option java_package = "org.wanderlinks.gel";

// TypeDef models a GEL type definition.
message TypeDef {
  // PrimitiveType enumerates supported primitive (built-in non-composite) data types.
  enum PrimitiveType {
    // Special value that indicates that an enum field is not initialized.
    PRIMITIVE_TYPE_UNSPECIFIED = 0;

    // Boolean values.
    PRIMITIVE_TYPE_BOOL = 1;

    // Sequence of bytes.
    PRIMITIVE_TYPE_BYTES = 2;

    // Real numeric values.
    PRIMITIVE_TYPE_REAL = 3;

    // Integer numeric values.
    PRIMITIVE_TYPE_INT = 4;

    // Strings.
    PRIMITIVE_TYPE_STRING = 5;

    // Durations.
    PRIMITIVE_TYPE_DURATION = 6;

    // Timestamps.
    PRIMITIVE_TYPE_TIMESTAMP = 7;
  }

  // FieldDef models a definition of a field of a struct or union.
  message FieldDef {
    // Field name.
    //
    // +Required
    string name = 1;

    // Field type.
    //
    // +Required
    TypeDef type = 2;

    // Specifies when the field will become (or had became) available.
    //
    // +Optional
    string available_since_version = 3;

    // Specifies when the field will become (or had became) deprecated.
    //
    // +Optional
    string deprecated_since_version = 4;
  }

  // StructTypeDef models a definition of a struct type.
  // A struct is an aggregate of one or more named values called fields.
  // Fields of a struct are accessed using "." notation.
  message StructTypeDef {
    // Field definitions by field names.
    //
    // +Required
    // +Constraints: $.keys.all(IsNotEmpty)  => field name is not set
    // +Constraints: $.values.all(IsPresent) => missing field definition
    map<string, FieldDef> field_def_by_name = 1;
  }

  // UnionTypeDef models a definition of a union type.
  // A union is an collection of one or more named values called fields,
  // where no more than one field can be initialized at the same time. 
  // Fields of a union are accessed using . notation.
  message UnionTypeDef {
    // Field definitions by field names.
    //
    // +Required
    // +Constraints: $.keys.all(IsNotEmpty)  : field name is not set
    // +Constraints: $.values.all(IsPresent) : missing field definition
    map<string, FieldDef> field_def_by_name = 1;
  }

  // EnumTypeDef models an enum type definition.
  message EnumTypeDef {
    // EnumValueDef models a definition of enum value.
    message EnumValueDef {
      // Enum name (value).
      //
      // +Required
      string name = 1;

      // Specifies when the enum value will become (or had became) available.
      //
      // +Optional
      google.protobuf.Timestamp available_since = 2;

      // Specifies when the enum value will become (or had became) deprecated.
      //
      // +Optional
      google.protobuf.Timestamp deprecated_since = 3;
    }

    // Enum value definitions by enum values.
    //
    // +Required
    // +Constraints: $.keys.all(IsNotEmpty)
    //  => [EMPTY_ENUM_DEF]: enum name is not set
    // +Constraints: $.values.all(IsPresent) 
    //  => [MISSING_ENUM]: missing enum definition
    map<string, EnumValueDef> enum_value_by_name = 1;
  }

  // ListTypeDef models a list type definition for either typed or generic
  // list.
  // A list is an ordered sequence of elements. Lists could be empty.
  // Elements of a list could be accessed by their indices using [] operator.
  message ListTypeDef {
    // Type definition of list elements.
    // If this field is not set, then this ListTypeDef defines a generic list type.
    //
    // +Optional
    TypeDef element_type = 1;
  }

  // SetTypeDef models a set type definition.
  // A set is a collection (potentially empty) of unique elements.
  message SetTypeDef {
    // Type definition of set elements.
    // If this field is not set, then this SetTypeDef defines a generic set type.
    //
    // +Optional
    TypeDef element_type = 1;
  }

  // MapTypeDef models a map type.
  // A map is a dictionary which values are accessed by corresponding keys.
  message MapTypeDef {
    // Type definition of map keys.
    // If this field is not set, then this MapTypeDef defines a generic map type.
    //
    // +Optional
    TypeDef key_type = 1;

    // Type definition of map values.
    // If this field is not set, then this MapTypeDef defines a generic map type.
    //
    // +Optional
    TypeDef value_type = 2;
  }

  // RangeTypeDef models a range type.
  message RangeTypeDef {
    // Range boundary type.
    // It should allow int, real, duration, and timestamp ranges.
    //
    // +Required
    TypeDef boundary_type = 1;
  }

  // AnyTypeDef models a placeholder type for generic types.
  message AnyTypeDef {
  }

  // FuncType models a function type.
  message FuncTypeDef {
    // Parameter declarations.
    //
    // +Optional
    // +Constraints: $.all(isPresent)
    repeated TypeDef param_types = 1;

    // Indicates that the last parameter of the function is a vararg parameter.
    //
    // +Required
    bool var_args = 2;

    // Type of the returned value.
    //
    // +Required
    TypeDef result_type = 3;
  }

  // Name of the type.
  //
  // +Required
  string name = 1;

  // Indicates if this type allows optional values (nil).
  //
  // +Required
  bool allows_optional_values = 2;

  // Mutually exclusive fields.
  //
  // +Required
  oneof kind {
    // Primitive type.
    //
    // +Optional
    PrimitiveType primitive_type = 10;

    // List type.
    //
    // +Optional
    ListTypeDef list_type = 11;

    // Set type.
    //
    // +Optional
    SetTypeDef set_type = 12;

    // Map type.
    //
    // +Optional
    MapTypeDef map_type = 13;

    // Range type.
    //
    // +Optional
    RangeTypeDef range_type = 14;

    // Struct type.
    //
    // +Optional
    StructTypeDef struct_type = 15;

    // Union type.
    //
    // +Optional
    UnionTypeDef union_type = 16;

    // Enum type.
    //
    // +Optional
    EnumTypeDef enum_type = 17;

    // Any type.
    //
    // +Optional
    AnyTypeDef any_type = 18;

    // Any type.
    //
    // +Optional
    FuncTypeDef func_type = 19;
  }
}

// Expr models a node of the Abstract Syntax Tree (AST) representing a GEL expression.
message Expr {
  // IntLiteral models an integer number literal.
  message IntLiteral {
    // Value.
    //
    // +Optional
    int64 value = 1;
  }

  // RealLiteral models a real number literal.
  message RealLiteral {
    // Value.
    //
    // +Optional
    double value = 1;
  }

  // StringLiteral models a string literal.
  message StringLiteral {
    // Value.
    //
    // +Optional
    string value = 1;
  }

  // BooleanLiteral models a boolean literal.
  message BooleanLiteral {
    // Value.
    //
    // +Optional
    bool value = 1;
  }

  // DurationLiteral models a duration literal.
  message DurationLiteral {
    // Value.
    // Examples of string represenation of duration literals: 
    //  2w    - two weeks
    //  1d    - one day
    //  3h    - three hours
    //  45min - forty five minutes
    //  17s   - seventeen seconds
    //  10ms  - ten miliseconds
    //  5mcs  - five microseconds
    //  70ns  - seventy nanoseconds 
    //
    // +Required
    google.protobuf.Duration value = 1;
  }

  // TimestampLiteral models a timestamp literal.
  message TimestampLiteral {
    // Value.
    // A string represenation of timestamp literals uses RFC 3339 syntax for date-time:
    //
    //   date-fullyear   = 4DIGIT
    //   date-month      = 2DIGIT  ; 01-12
    //   date-mday       = 2DIGIT  ; 01-28, 01-29, 01-30, 01-31 based on
    //                             ; month/year
    //   time-hour       = 2DIGIT  ; 00-23
    //   time-minute     = 2DIGIT  ; 00-59
    //   time-second     = 2DIGIT  ; 00-58, 00-59, 00-60 based on leap second
    //                             ; rules
    //   time-secfrac    = "." 1*DIGIT
    //   time-numoffset  = ("+" / "-") time-hour ":" time-minute
    //   time-offset     = "Z" / time-numoffset
    //   
    //   partial-time    = time-hour ":" time-minute ":" time-second
    //                     [time-secfrac]
    //   full-date       = date-fullyear "-" date-month "-" date-mday
    //   full-time       = partial-time time-offset
    //   
    //   date-time       = full-date "T" full-time
    //
    // Examples:
    //   1985-04-12T23:20:50.52Z
    //     20 minutes and 50.52 seconds after the 23rd hour of April 12th, 1985 in UTC.
    //
    //   1996-12-19T16:39:57-08:00
    //     39 minutes and 57 seconds after the 16th hour of December 19th, 1996 with an offset of -08:00 
    //     from UTC (Pacific Standard Time).  Note that this is equivalent to 1996-12-20T00:39:57Z in UTC.
    //
    //   1990-12-31T23:59:60Z
    //     the leap second inserted at the end of 1990.
    //
    //   1990-12-31T15:59:60-08:00
    //     the same leap second in Pacific Standard Time, 8 hours behind UTC.
    //
    //   1937-01-01T12:00:27.87+00:20
    //     January 1, 1937, Netherlands time.  Standard time in the Netherlands was exactly 19
    //     minutes and 32.13 seconds ahead of UTC by law from 1909-05-01 through 1937-06-30.
    //
    //   P.S. Leap year detection: (year % 4 == 0 && (year % 100 != 0 || year % 400 == 0))
    //
    // +Optional
    google.protobuf.Timestamp value = 1;
  }

  // EnumLiteral models an enum literal.
  message EnumLiteral {
    // Value.
    //
    // +Required
    string name = 1;
  }

  // RangeExpr models an open or closed contiguous range of values.
  // +Constraints: $.type.primitive_type in 
  //     {PRIMITIVE_TYPE_INT, PRIMITIVE_TYPE_REAL, PRIMITIVE_TYPE_DURATION, PRIMITIVE_TYPE_TIMESTAMP}
  // +Constraints: $lower_bound.type == $upper_bound.type
  message RangeExpr {
    // Indicates if the range is open (true) or closed (false).
    // A range is called an *open range* when the upper boundary is NOT INCLUDED
    // in the range.
    // A range is called a *closed range* when the upper boundary is INCLUDED
    // in the range.
    //
    // +Required
    bool open_range = 1;

    // Lower boundary of the range.
    //
    // +Required
    Expr lower_bound = 2;

    // Upper boundary of the range.
    // +Required
    Expr upper_bound = 3;
  }

  // SetExpr models a set of values of the same type.
  message SetExpr {
    // Element type.
    //
    // +Required
    TypeDef element_type = 1;

    // Elements of the set.
    //
    // +Optional
    // +Constraints: $.map($1.type).unique().size() == 1
    //              : all elements of a set must have the same type
    repeated Expr elements = 2;
  }

  // ListExpr models a list of values of the same type.
  message ListExpr {
    // Element type.
    //
    // +Required
    TypeDef element_type = 1;

    // Elements of the list.
    //
    // +Optional
    // +Constraints: $.map($1.type).unique().size() <= 1
    //              : all elements of a list must have the same type
    repeated Expr elements = 2;
  }

  // MapExpr models a dictionary.
  message MapExpr {
    // Key type.
    //
    // +Required
    TypeDef key_type = 1;

    // Value type.
    //
    // +Required
    TypeDef value_type = 2;

    // Keys.
    //
    // +Optional
    // +Constraints: $.map($1.type).unique().size() <= 1
    //              : all keys of a map must have the same type
    // +Constraints: $.size() == $.unique().size()
    //              : all keys of a map must be unique
    repeated Expr keys = 3;

    // Values.
    //
    // +Optional
    // +Constraints: $.map($1.type).unique().size() <= 1
    //              : all values of a map must have the same type
    // +Constraints: len($) == len($keys)
    //              : number of keys and values should be the same
    repeated Expr values = 4;
  }

  // PrefixUnaryOpExpr models a prefix unary operation expression: {op} {RHS}.
  // The following operations must be supported:
  //
  // Numeric Negation Operation: "-" {RHS}
  // +==========+=============+========================================+
  // | RHS Type | Result Type | Result Description                     |
  // +==========+=============+========================================+
  // | int      | int         | Returns -1 * RHS                       |
  // +----------+-------------+----------------------------------------+
  // | real     | real        | Returns -1 * RHS                       |
  // +----------+-------------+----------------------------------------+
  //
  // Logical Negation Operation: "not" | "!" {RHS}
  // +==========+=============+========================================+
  // | RHS Type | Result Type | Result Description                     |
  // +==========+=============+========================================+
  // | bool     | bool        | TRUE if RHS if FALSE, and FALSE        |
  // |          |             | otherwise.                             |
  // +----------+-------------+----------------------------------------+
  //
  // Bitwise NOT Operation: "~" {RHS}
  // +==========+=============+========================================+
  // | RHS Type | Result Type | Result Description                     |
  // +==========+=============+========================================+
  // | int      | int         | Inverts all bits in RHS.               |
  // +----------+-------------+----------------------------------------+
  message PrefixUnaryOpExpr {
    // Operator symbol.
    //
    // +Required
    string op = 1;

    // Operand.
    //
    // +Required
    Expr rhs = 2;
  }

  // PostfixUnaryOpExpr models a postfix unary operation expression: {LHS} {op}.
  // The following operations must be supported:
  //
  // Unwrap Optional Value Operation: {LHS} "!"
  // +==========+=============+========================================+
  // | LHS Type | Result Type | Result Description                     |
  // +==========+=============+========================================+
  // | T?       | T           | T if LHS is set, otherwise throws an   |
  // |          |             | exception.                             |
  // +----------+-------------+----------------------------------------+
  message PostfixUnaryOpExpr {
    // Operator symbol.
    //
    // +Required
    string op = 1;

    // Operand.
    //
    // +Required
    Expr lhs = 2;
  }

  // BinaryOpExpr models a binary operation expression (A op B).
  // The following operations must be supported:
  //
  // Addition Operation: {LHS} "+" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | string   | string   | string      | String concatenation        |
  // +----------+----------+-------------+-----------------------------+
  // | int      | int      | int         | Sum of two integer values   |
  // +----------+----------+-------------+-----------------------------+
  // | int      | real     | real        | Sum of two numeric values   |
  // +----------+----------+-------------+-----------------------------+
  // | real     | int      | real        | Sum of two numeric values   |
  // +----------+----------+-------------+-----------------------------+
  // | real     | real     | real        | Sum of two real values      |
  // +----------+----------+-------------+-----------------------------+
  // | duration | duration | duration    | Sum of two durations        |
  // +----------+----------+-------------+-----------------------------+
  // | duration | timestamp| timestamp   | Timestamp RHS advanced by   |
  // |          |          |             | duration LHS.               |
  // +----------+----------+-------------+-----------------------------+
  // | timestamp| duration | timestamp   | Timestamp LHS advanced by   |
  // |          |          |             | duration RHS.               |
  // +----------+----------+-------------+-----------------------------+
  // | set<T>   | T        | set<T>      | New set that contains all   |
  // |          |          |             | elements from the LHS and   |
  // |          |          |             | RHS element.                |
  // |          |          |             | If the LHS set already      |
  // |          |          |             | has RHS, the result is      |
  // |          |          |             | LHS set.                    |
  // +----------+----------+-------------+-----------------------------+
  // | T        | set<T>   | set<T>      | New set that contains all   |
  // |          |          |             | elements from the RHS and   |
  // |          |          |             | LHS element.                |
  // |          |          |             | If the RHS set already      |
  // |          |          |             | has LHS, the result is      |
  // |          |          |             | RHS set.                    |
  // +----------+----------+-------------+-----------------------------+
  // | set<T>   | set<T>   | set<T>      | Union of two sets.          |
  // +----------+----------+-------------+-----------------------------+
  // | list<T>  | T        | list<T>     | New list that is created    |
  // |          |          |             | from LHS by appending RHS   |
  // |          |          |             | to the end of the list.     |
  // +----------+----------+-------------+-----------------------------+
  // | T        | list<T>  | list<T>     | New list that is created    |
  // |          |          |             | from RHS by inserting LHS   |
  // |          |          |             | as the first element.       |
  // +----------+----------+-------------+-----------------------------+
  // | list<T>  | list<T>  | list<T>     | Concatenation of two        |
  // |          |          |             | lists.                      |
  // +==========+==========+=============+=============================+
  //
  // Subtraction Operation: {LHS} "-" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | int      | int      | int         | Difference between two      |
  // |          |          |             | integer values.             | 
  // +----------+----------+-------------+-----------------------------+
  // | int      | real     | real        | Difference between two      |
  // |          |          |             | numeric values.             | 
  // +----------+----------+-------------+-----------------------------+
  // | real     | int      | real        | Difference between two      |
  // |          |          |             | numeric values.             | 
  // +----------+----------+-------------+-----------------------------+
  // | real     | real     | real        | Difference between two      |
  // |          |          |             | real values.                | 
  // +----------+----------+-------------+-----------------------------+
  // | duration | duration | duration    | Difference between two      |
  // |          |          |             | durations.                  | 
  // +----------+----------+-------------+-----------------------------+
  // | timestamp| timestamp| duration    | Difference between two      |
  // |          |          |             | timestamps.                 | 
  // +----------+----------+-------------+-----------------------------+
  // | timestamp| duration | timestamp   | Timestamp LHS moved back by |
  // |          |          |             | duration RHS.               |
  // +----------+----------+-------------+-----------------------------+
  // | set<T>   | T        | set<T>      | New set that is created     |
  // |          |          |             | by removing RHS from LHS.   |
  // +----------+----------+-------------+-----------------------------+
  // | set<T>   | set<T>   | set<T>      | New set that is created     |
  // |          |          |             | by removing all RHS elements|
  // |          |          |             | from LHS elements.          |
  // +----------+----------+-------------+-----------------------------+
  // | list<T>  | T        | list<T>     | New list that is created    |
  // |          |          |             | from LHS by removing        |
  // |          |          |             | RHS element.                |
  // +==========+==========+=============+=============================+
  //
  // Division Operation: {LHS} "/" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | int      | int      | int         | Quotient of the divison     |
  // |          |          |             | of LHS by RHS integer       |
  // |          |          |             | values.                     |  
  // +----------+----------+-------------+-----------------------------+
  // | int      | real     | real        | Difference between two      |
  // |          |          |             | numeric values.             | 
  // +----------+----------+-------------+-----------------------------+
  // | real     | int      | real        | Difference between two      |
  // |          |          |             | numeric values.             | 
  // +----------+----------+-------------+-----------------------------+
  // | real     | real     | real        | Difference between two      |
  // |          |          |             | real values.                | 
  // +----------+----------+-------------+-----------------------------+
  // | duration | int      | duration    | Quotient of the divison     |
  // |          |          |             | of LHS by RHS.              |  
  // +----------+----------+-------------+-----------------------------+
  // | duration | duration | int         | Quotient of the divison     |
  // |          |          |             | of LHS by RHS.              |  
  // +==========+==========+=============+=============================+
  //
  // Multiplication Operation: {LHS} "*" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | int      | int      | int         | Product of LHS and RHS.     |
  // +----------+----------+-------------+-----------------------------+
  // | int      | real     | real        | Product of LHS and RHS.     |
  // +----------+----------+-------------+-----------------------------+
  // | real     | int      | real        | Product of LHS and RHS.     |
  // +----------+----------+-------------+-----------------------------+
  // | real     | real     | real        | Product of LHS and RHS.     |
  // +----------+----------+-------------+-----------------------------+
  // | duration | int      | duration    | Product of LHS by RHS.      |  
  // +----------+----------+-------------+-----------------------------+
  // | int      | duration | duration    | Product of LHS by RHS.      |  
  // +==========+==========+=============+=============================+
  //
  // Remainder (Modulus) Operation: {LHS} "%" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | int      | int      | int         | Reminder of the division    |
  // |          |          |             | of LHS by RHS integer       |
  // |          |          |             | values.                     |
  // |          |          |             | In cases where the LHS is   |
  // |          |          |             | negative, the result is a   |
  // |          |          |             | negative remainder.         |  
  // +----------+----------+-------------+-----------------------------+
  // | duration | int      | duration    | Reminder of the division    |
  // |          |          |             | of LHS by RHS.              |  
  // |          |          |             | In cases where the LHS is   |
  // |          |          |             | negative, the result is a   |
  // |          |          |             | negative remainder.         |  
  // +==========+==========+=============+=============================+
  //
  // Equality Operation: {LHS} "==" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | string   | string   | bool        | TRUE if the LHS and RHS     |
  // |          |          |             | strings are exactly the     |
  // |          |          |             | same and FALSE otherwise.   |
  // +----------+----------+-------------+-----------------------------+
  // | int      | int      | bool        | TRUE if the LHS and RHS     |
  // |          |          |             | integers are exactly the    |
  // |          |          |             | same and FALSE otherwise.   |
  // +----------+----------+-------------+-----------------------------+
  // | real     | real     | bool        | TRUE if the LHS and RHS     |
  // |          |          |             | real numbers are exactly the|
  // |          |          |             | same and FALSE otherwise.   |
  // +----------+----------+-------------+-----------------------------+
  // | bool     | bool     | bool        | TRUE if the LHS and RHS     |
  // |          |          |             | values are exactly the      |
  // |          |          |             | same and FALSE otherwise.   |
  // +----------+----------+-------------+-----------------------------+
  // | bytes    | bytes    | bool        | TRUE if the LHS and RHS     |
  // |          |          |             | byte strings are exactly the|
  // |          |          |             | same and FALSE otherwise.   |
  // +----------+----------+-------------+-----------------------------+
  // | duration | duration | bool        | TRUE if the LHS and RHS     |
  // |          |          |             | durations are exactly the   |
  // |          |          |             | same and FALSE otherwise.   |
  // +----------+----------+-------------+-----------------------------+
  // | timestamp| timestamp| bool        | TRUE if the LHS and RHS     |
  // |          |          |             | timestamps are exactly the  |
  // |          |          |             | same and FALSE otherwise.   |
  // +----------+----------+-------------+-----------------------------+
  // | set<T>   | set<T>   | bool        | TRUE if the LHS and RHS     |
  // |          |          |             | sets are exactly the        |
  // |          |          |             | same and FALSE otherwise.   |
  // +----------+----------+-------------+-----------------------------+
  // | list<T>  | list<T>  | bool        | TRUE if the LHS and RHS     |
  // |          |          |             | lists are exactly the       |
  // |          |          |             | same and FALSE otherwise.   |
  // +----------+----------+-------------+-----------------------------+
  // | map<K,V> | map<K,V> | bool        | TRUE if the LHS and RHS     |
  // |          |          |             | maps are exactly the        |
  // |          |          |             | same and FALSE otherwise.   |
  // +----------+----------+-------------+-----------------------------+
  // | struct   | struct   | bool        | TRUE if the LHS and RHS     |
  // |          |          |             | structs are exactly the     |
  // |          |          |             | same and FALSE otherwise.   |
  // +==========+==========+=============+=============================+
  //
  // Non-Equality Operation: {LHS} "!=" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | string   | string   | bool        | FALSE if the LHS and RHS    |
  // |          |          |             | strings are exactly the     |
  // |          |          |             | same and TRUE otherwise.    |
  // +----------+----------+-------------+-----------------------------+
  // | int      | int      | bool        | FALSE if the LHS and RHS    |
  // |          |          |             | integers are exactly the    |
  // |          |          |             | same and TRUE otherwise.    |
  // +----------+----------+-------------+-----------------------------+
  // | real     | real     | bool        | FALSE if the LHS and RHS    |
  // |          |          |             | real numbers are exactly the|
  // |          |          |             | same and TRUE otherwise.    |
  // +----------+----------+-------------+-----------------------------+
  // | bool     | bool     | bool        | FALSE if the LHS and RHS    |
  // |          |          |             | values are exactly the      |
  // |          |          |             | same and TRUE otherwise.    |
  // +----------+----------+-------------+-----------------------------+
  // | bytes    | bytes    | bool        | FALSE if the LHS and RHS    |
  // |          |          |             | byte strings are exactly the|
  // |          |          |             | same and TRUE otherwise.    |
  // +----------+----------+-------------+-----------------------------+
  // | duration | duration | bool        | FALSE if the LHS and RHS    |
  // |          |          |             | durations are exactly the   |
  // |          |          |             | same and TRUE otherwise.    |
  // +----------+----------+-------------+-----------------------------+
  // | timestamp| timestamp| bool        | FALSE if the LHS and RHS    |
  // |          |          |             | timestamps are exactly the  |
  // |          |          |             | same and TRUE otherwise.    |
  // +----------+----------+-------------+-----------------------------+
  // | set<T>   | set<T>   | bool        | FALSE if the LHS and RHS    |
  // |          |          |             | sets are exactly the        |
  // |          |          |             | same and TRUE otherwise.    |
  // +----------+----------+-------------+-----------------------------+
  // | list<T>  | list<T>  | bool        | FALSE if the LHS and RHS    |
  // |          |          |             | lists are exactly the       |
  // |          |          |             | same and TRUE otherwise.    |
  // +----------+----------+-------------+-----------------------------+
  // | map<K,V> | map<K,V> | bool        | FALSE if the LHS and RHS    |
  // |          |          |             | maps are exactly the        |
  // |          |          |             | same and TRUE otherwise.    |
  // +----------+----------+-------------+-----------------------------+
  // | struct   | struct   | bool        | FALSE if the LHS and RHS    |
  // |          |          |             | structs are exactly the     |
  // |          |          |             | same and TRUE otherwise.    |
  // +==========+==========+=============+=============================+
  //
  // Case-Insenitive String Equality Operation: {LHS} "~~" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | string   | string   | bool        | TRUE if the LHS and RHS     |
  // |          |          |             | strings are equal ignoring  |
  // |          |          |             | case differences and        |
  // |          |          |             | FALSE otherwise.            |
  // +==========+==========+=============+=============================+
  //
  // Less-Than Operation: {LHS} "<" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | string   | string   | bool        | TRUE if the LHS is          |
  // |          |          |             | lexicographically less than |
  // |          |          |             | the RHS and FALSE otherwise.|
  // +----------+----------+-------------+-----------------------------+
  // | int      | int      | bool        | TRUE if the LHS less than   |
  // |          |          |             | RHS and FALSE otherwise.    |
  // +----------+----------+-------------+-----------------------------+
  // | int      | real     | bool        | TRUE if the LHS less than   |
  // |          |          |             | RHS and FALSE otherwise.    |
  // +----------+----------+-------------+-----------------------------+
  // | real     | real     | bool        | TRUE if the LHS less than   |
  // |          |          |             | RHS and FALSE otherwise.    |
  // +----------+----------+-------------+-----------------------------+
  // | real     | int      | bool        | TRUE if the LHS less than   |
  // |          |          |             | RHS and FALSE otherwise.    |
  // +----------+----------+-------------+-----------------------------+
  // | duration | duration | bool        | TRUE if the LHS less than   |
  // |          |          |             | RHS and FALSE otherwise.    |
  // +----------+----------+-------------+-----------------------------+
  // | timestamp| timestamp| bool        | TRUE if the LHS less than   |
  // |          |          |             | RHS and FALSE otherwise.    |
  // +----------+----------+-------------+-----------------------------+
  // | set<T>   | set<T>   | bool        | TRUE if the LHS is a subset |
  // |          |          |             | of RHS and FALSE otherwise. |
  // +----------+----------+-------------+-----------------------------+
  // | list<T>  | list<T>  | bool        | TRUE if the LHS is          |
  // |          |          |             | lexicographically less than |
  // |          |          |             | the RHS and FALSE otherwise.|
  // +==========+==========+=============+=============================+
  //
  // Less-Or-Equal-To Operation: {LHS} "<=" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | string   | string   | bool        | TRUE if the LHS is the same |
  // |          |          |             | as RHS or lexicographically |
  // |          |          |             | less than the RHS           |
  // |          |          |             | and FALSE otherwise.        |
  // +----------+----------+-------------+-----------------------------+
  // | int      | int      | bool        | TRUE if the LHS less than   |
  // |          |          |             | or equal to RHS             |
  // |          |          |             | and FALSE otherwise.        |
  // +----------+----------+-------------+-----------------------------+
  // | int      | real     | bool        | TRUE if the LHS less than   |
  // |          |          |             | or equal to RHS             |
  // |          |          |             | and FALSE otherwise.        |
  // +----------+----------+-------------+-----------------------------+
  // | real     | real     | bool        | TRUE if the LHS less than   |
  // |          |          |             | or equal to RHS             |
  // |          |          |             | and FALSE otherwise.        |
  // +----------+----------+-------------+-----------------------------+
  // | real     | int      | bool        | TRUE if the LHS less than   |
  // |          |          |             | or equal to RHS             |
  // |          |          |             | and FALSE otherwise.        |
  // +----------+----------+-------------+-----------------------------+
  // | duration | duration | bool        | TRUE if the LHS less than   |
  // |          |          |             | or equal to RHS             |
  // |          |          |             | and FALSE otherwise.        |
  // +----------+----------+-------------+-----------------------------+
  // | timestamp| timestamp| bool        | TRUE if the LHS less than   |
  // |          |          |             | or equal to RHS             |
  // |          |          |             | and FALSE otherwise.        |
  // +----------+----------+-------------+-----------------------------+
  // | set<T>   | set<T>   | bool        | TRUE if the LHS is the same |
  // |          |          |             | as RHS or LHS is a subset   |
  // |          |          |             | of RHS, and FALSE otherwise.|
  // +----------+----------+-------------+-----------------------------+
  // | list<T>  | list<T>  | bool        | TRUE if the LHS is the same |
  // |          |          |             | as RHS or lexicographically |
  // |          |          |             | less than the RHS           |
  // |          |          |             | and FALSE otherwise.        |
  // +==========+==========+=============+=============================+
  //
  // Greater-Than Operation: {LHS} ">" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | string   | string   | bool        | TRUE if the LHS is          |
  // |          |          |             | lexicographically greater   | 
  // |          |          |             | than RHS and TRUE otherwise.|
  // +----------+----------+-------------+-----------------------------+
  // | int      | int      | bool        | TRUE if the LHS greater     |
  // |          |          |             | than RHS and TRUE otherwise.|
  // +----------+----------+-------------+-----------------------------+
  // | int      | real     | bool        | TRUE if the LHS greater     |
  // |          |          |             | than RHS and TRUE otherwise.|
  // +----------+----------+-------------+-----------------------------+
  // | real     | real     | bool        | TRUE if the LHS greater     |
  // |          |          |             | than RHS and TRUE otherwise.|
  // +----------+----------+-------------+-----------------------------+
  // | real     | int      | bool        | TRUE if the LHS greater     |
  // |          |          |             | than RHS and TRUE otherwise.|
  // +----------+----------+-------------+-----------------------------+
  // | duration | duration | bool        | TRUE if the LHS greater     |
  // |          |          |             | than RHS and TRUE otherwise.|
  // +----------+----------+-------------+-----------------------------+
  // | timestamp| timestamp| bool        | TRUE if the LHS greater     |
  // |          |          |             | than RHS and TRUE otherwise.|
  // +----------+----------+-------------+-----------------------------+
  // | set<T>   | set<T>   | bool        | TRUE if the LHS is a        |
  // |          |          |             | superset of RHS             |
  // |          |          |             | and FALSE otherwise.        |
  // +----------+----------+-------------+-----------------------------+
  // | list<T>  | list<T>  | bool        | TRUE if the LHS is          |
  // |          |          |             | lexicographically greater   | 
  // |          |          |             | than RHS and TRUE otherwise.|
  // +==========+==========+=============+=============================+
  //
  // Greater-Or-Equal-To Operation: {LHS} ">=" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | string   | string   | bool        | TRUE if the LHS is the same |
  // |          |          |             | as RHS or lexicographically |
  // |          |          |             | greater than the RHS        |
  // |          |          |             | and FALSE otherwise.        |
  // +----------+----------+-------------+-----------------------------+
  // | int      | int      | bool        | TRUE if the LHS greater than|
  // |          |          |             | or equal to RHS             |
  // |          |          |             | and FALSE otherwise.        |
  // +----------+----------+-------------+-----------------------------+
  // | int      | real     | bool        | TRUE if the LHS greater than|
  // |          |          |             | or equal to RHS             |
  // |          |          |             | and FALSE otherwise.        |
  // +----------+----------+-------------+-----------------------------+
  // | real     | real     | bool        | TRUE if the LHS greater than|
  // |          |          |             | or equal to RHS             |
  // |          |          |             | and FALSE otherwise.        |
  // +----------+----------+-------------+-----------------------------+
  // | real     | int      | bool        | TRUE if the LHS greater than|
  // |          |          |             | or equal to RHS             |
  // |          |          |             | and FALSE otherwise.        |
  // +----------+----------+-------------+-----------------------------+
  // | duration | duration | bool        | TRUE if the LHS greater than|
  // |          |          |             | or equal to RHS             |
  // |          |          |             | and FALSE otherwise.        |
  // +----------+----------+-------------+-----------------------------+
  // | timestamp| timestamp| bool        | TRUE if the LHS greater than|
  // |          |          |             | or equal to RHS             |
  // |          |          |             | and FALSE otherwise.        |
  // +----------+----------+-------------+-----------------------------+
  // | set<T>   | set<T>   | bool        | TRUE if the LHS is the same |
  // |          |          |             | as RHS or LHS is a superset |
  // |          |          |             | of RHS, and FALSE otherwise.|
  // +----------+----------+-------------+-----------------------------+
  // | list<T>  | list<T>  | bool        | TRUE if the LHS is the same |
  // |          |          |             | as RHS or lexicographically |
  // |          |          |             | greater than the RHS        |
  // |          |          |             | and FALSE otherwise.        |
  // +==========+==========+=============+=============================+
  //
  // Nil-Coalescing Operation: {LHS} "??" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | T?       | T        | T           | Unwrapped LHS if the LHS is |
  // |          |          |             | not nil, otherwise RHS.     |
  // +==========+==========+=============+=============================+
  //
  // Closed Range Generator: {LHS} "..." {RHS}
  // +==========+==========+===============+=============================+
  // | LHS Type | RHS Type | Result Type   | Result Description          |
  // +==========+==========+===============+=============================+
  // | T        | T        | range<T>      | Closed range of             |
  // |          |          |               | values where LHS is the     |
  // |          |          |               | lower boundary and RHS is   |
  // |          |          |               | the upper boundary.         |
  // +==========+==========+===============+=============================+
  //
  // Open Range Generator: {LHS} "..<" {RHS}
  // +==========+==========+===============+=============================+
  // | LHS Type | RHS Type | Result Type   | Result Description          |
  // +==========+==========+===============+=============================+
  // | T        | T        | range<T>      | Open range of values        |
  // |          |          |               | where LHS is the            |
  // |          |          |               | lower boundary and RHS is   |
  // |          |          |               | the upper boundary.         |
  // +==========+==========+===============+=============================+
  //
  // Operation IN: {LHS} "in" {RHS}
  // +==========+===============+=============+=============================+
  // | LHS Type | RHS Type      | Result Type | Result Description          |
  // +==========+===============+=============+=============================+
  // | T        | set<T>        | bool        | TRUE if LHS is a member of  |
  // |          |               |             | of RHS, and FALSE otherwise.|
  // +----------+---------------+-------------+-----------------------------+
  // | set<T>   | set<T>        | bool        | TRUE if LHS is a subset of  |
  // |          |               |             | of RHS, and FALSE otherwise.|
  // +----------+---------------+-------------+-----------------------------+
  // | T        | list<T>       | bool        | TRUE if RHS contains        |
  // |          |               |             | LHS, and FALSE otherwise.   |
  // +----------+---------------+-------------+-----------------------------+
  // | list<T>  | list<T>       | bool        | TRUE if RHS contains        |
  // |          |               |             | LHS, and FALSE otherwise.   |
  // +----------+---------------+-------------+-----------------------------+
  // | K        | map<K,V>      | bool        | TRUE if RHS contains key    |
  // |          |               |             | LHS, and FALSE otherwise.   |
  // +----------+---------------+-------------+-----------------------------+
  // | T        | range<T>      | bool        | TRUE if LHS is in the range |
  // |          |               |             | RHS, and FALSE otherwise.   |
  // +==========+===============+=============+=============================+
  //
  // Operation Logical AND: {LHS} "&&" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | bool     | bool     | bool        | TRUE if both LHS and RHS are|
  // |          |          |             | TRUE, and FALSE otherwise.  |
  // +==========+==========+=============+=============================+
  //
  // Operation Logical OR: {LHS} "||" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | bool     | bool     | bool        | TRUE if either or both LHS  |
  // |          |          |             | and RHS are TRUE,           |
  // |          |          |             | and FALSE otherwise.        |
  // +==========+==========+=============+=============================+
  //
  // Operation EXclusive OR: {LHS} "^^" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | bool     | bool     | bool        | TRUE if both LHS            |
  // |          |          |             | and RHS are different,      |
  // |          |          |             | and FALSE otherwise.        |
  // +==========+==========+=============+=============================+
  //
  // Operation Pattern Matching: {LHS} "~=" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | string   | string   | bool        | TRUE if LHS matches regular |
  // |          |          |             | expression (pattern) RHS,   |
  // |          |          |             | and FALSE otherwise.        |
  // +==========+==========+=============+=============================+
  //
  // Subscript Operation: {LHS} "[" {RHS} "]"
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | list<T>  | int      | T           | Element of the list at the  |
  // |          |          |             | position specified by RHS,  |
  // |          |          |             | or throws an exception if   |
  // |          |          |             | the index out of range.     |
  // +----------+----------+-------------+-----------------------------+
  // | map<K,V> | K        | V?          | Element of the map at the   |
  // |          |          |             | position specified by RHS.  |
  // +==========+==========+=============+=============================+
  //
  // Operation Bitwise OR: {LHS} "|" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | int      | int      | int         | Bitwise OR of LHS and RHS.  |
  // +==========+==========+=============+=============================+
  //
  // Operation Bitwise AND: {LHS} "&" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | int      | int      | int         | Bitwise AND of LHS and RHS. |
  // +==========+==========+=============+=============================+
  //
  // Operation Bitwise XOR: {LHS} "^" {RHS}
  // +==========+==========+=============+=============================+
  // | LHS Type | RHS Type | Result Type | Result Description          |
  // +==========+==========+=============+=============================+
  // | int      | int      | int         | Bitwise XOR of LHS and RHS. |
  // +==========+==========+=============+=============================+
  message BinaryOpExpr {
    // Operator symbol.
    //
    // +Required
    string op = 1;

    // Left hand side operand.
    //
    // +Required
    Expr lhs = 2;

    // Right hand side operand.
    //
    // +Required
    Expr rhs = 3;
  }

  // TernaryOpExpr models a ternary operation (a ? b : c).
  //
  // Ternary Operation: {OP1} "?" {OP2} ":" {OP3}
  // +==========+==========+==========+=============+===========================+
  // | OP1 Type | OP2 Type | OP3 Type | Result Type | Result Description        |
  // +==========+==========+==========+=============+===========================+
  // | bool     | T        | T        | T           | OP2 if OP1 is TRUE or OP3 |
  // |          |          |          |             | otherwise.                |
  // +==========+==========+==========+=============+===========================+
  message TernaryOpExpr {
    // Predicate which is used to select the result of the operation.
    //
    // +Required
    Expr predicate = 1;

    // Result of the operation if the predicate is evaluated to true.
    //
    // +Required
    Expr true_expr = 2;

    // Result of the operation if the predicate is evaluated to false.
    //
    // +Required
    Expr false_expr = 3;
  }

  // ConstRef models a reference to a constant value.
  message ConstRefExpr {
    // Constant name.
    //
    // +Required
    string name = 1;
  }

  // FieldRefExpr models a reference to a struct field.
  message FieldRefExpr {
    // Fully qualified name of the struct that contains the field.
    // The first element must be the name of the top level struct in the parsing context.
    //
    // +Required
    // +Constraints: $.all(NotEmpty)
    repeated string struct_ref = 1;

    // Field name.
    //
    // +Required
    string name = 2;
  }

  // FuncCallExpr models a function call expression.
  message FuncCallExpr {
    // Function ID.
    //
    // +Required
    string id = 1;

    // Function name.
    //
    // +Required
    string name = 2;

    // Function arguments.
    //
    // +Optional
    // +Constraints: $.all(IsPresent)
    repeated Expr args = 3;
  }

  // ParamRefExpr models a reference to parameter of a function or expression.
  message ParamRefExpr {
    // Parameter name.
    //
    // +Required
    string name = 1;
  }

  //// End of nested definitions.

  // Type of the expression represented by the node.
  //
  // +Required
  TypeDef type = 1;

  // Mutually exclusive fields.
  //
  // +Required
  oneof kind {
    // +Optional
    IntLiteral int_literal = 2;

    // +Optional
    RealLiteral real_literal = 3;

    // +Optional
    StringLiteral string_literal = 4;

    // +Optional
    BooleanLiteral boolean_literal = 5;

    // +Optional
    DurationLiteral duration_literal = 6;

    // +Optional
    TimestampLiteral timestamp_literal = 7;

    // +Optional
    EnumLiteral enum_literal = 8;

    // +Optional
    RangeExpr range_expr = 9;

    // +Optional
    PrefixUnaryOpExpr prefix_unary_op_expr = 10;

    // +Optional
    PostfixUnaryOpExpr postfix_unary_op_expr = 11;

    // +Optional
    BinaryOpExpr binary_op_expr = 12;

    // +Optional
    TernaryOpExpr ternary_op_expr = 13;

    // +Optional
    SetExpr set_expr = 14;

    // +Optional
    ListExpr list_expr = 15;

    // +Optional
    MapExpr map_expr = 16;

    // +Optional
    ConstRefExpr const_ref = 17;

    // +Optional
    FieldRefExpr field_ref = 18;

    // +Optional
    FuncCallExpr func_call = 19;

    // +Optional
    ParamRefExpr param_ref = 20;
  }
}

// ParamDecl models a function parameter declaration.
// TODO(vmiksonov): rename it to ParamDef
message ParamDecl {
  // Name of the parameter.
  //
  // +Required
  string name = 1;

  // Type of the parameter.
  //
  // +Required
  TypeDef type = 2;

  // Default value of the parameter.
  //
  // +Optional
  Expr default_value = 3;

  // Variable-length arguments (varargs) flag.
  // If it's TRUE, then this parameter matches any number of arguments of 
  // the parameter's type, including none (0).
  // Only the last parameter of a function or a parameterized expression can be varargs.
  //
  // +Optional
  bool var_args = 4;
}

// FuncDecl models a function declaration.
// The following functions must be supported:
//
// IsZero(int)      -> bool
// IsZero(real)     -> bool
// IsZero(duration) -> bool
//
// IsPositive(int)      -> bool
// IsPositive(real)     -> bool
// IsPositive(duration) -> bool
//
// IsNegative(int)      -> bool
// IsNegative(real)     -> bool
// IsNegative(duration) -> bool
//
// IsPresent(T?) -> bool
//
// IsAbsent(T?) -> bool
//
// IsAbsentOrEmpty(list<T>?)  -> bool
// IsAbsentOrEmpty(map<K,V>?) -> bool
// IsAbsentOrEmpty(set<T>?)   -> bool
// IsAbsentOrEmpty(string?)   -> bool
//
// IsPresentAndNotEmpty(list<T>?)  -> bool
// IsPresentAndNotEmpty(map<K,V>?) -> bool
// IsPresentAndNotEmpty(set<T>?)   -> bool
// IsPresentAndNotEmpty(string?)   -> bool
//
// IsEmpty(list<T>)  -> bool
// IsEmpty(map<K,V>) -> bool
// IsEmpty(set<T>)   -> bool
// IsEmpty(string)   -> bool
//
// IsNotEmpty(list<T>)  -> bool
// IsNotEmpty(map<K,V>) -> bool
// IsNotEmpty(set<T>)   -> bool
// IsNotEmpty(string)   -> bool
//
// IsBlank(string) -> bool
//
// IsNonBlank(string) -> bool
//
// Len(list<T>)  -> int
// Len(map<K,V>) -> int
// Len(set<T>)   -> int
// Len(string)   -> int
//
// list<T>.Count(f(T) -> bool) -> int
// set<T> .Count(f(T) -> bool) -> int
//
// list<T>.Min() -> T
// set<T> .Min() -> T
//
// list<T>.Max() -> T
// set<T> .Max() -> T
//
// list<T> .Filter((T) -> bool)   -> list<T>
// map<K,V>.Filter((K,V) -> bool) -> map<K,V>
// set<T>  .Filter((T) -> bool)   -> set<T>
//
// list<T1>.Map((T1) -> T2) -> list<T2>
// set<T1> .Map((T1) -> T2) -> set<T2>
//
// list<T>.Any((T) -> bool) -> bool
// set<T> .Any((T) -> bool) -> bool
//
// list<T>.All((T) -> bool) -> bool
// set<T> .All((T) -> bool) -> bool
//
// list<T>.None((T) -> bool) -> bool
// set<T> .None((T) -> bool) -> bool
//
// list<T>.Find((T) -> bool) -> T?
// set<T> .Find((T) -> bool) -> T?
//
// list<T>.Reduce(R, (R, T) -> R) -> R
// set<T> .Reduce(R, (R, T) -> R) -> R
//
// list<T>.Slice(int)      -> list<T>
// list<T>.Slice(int, int) -> list<T>
//
// map<K,V>.Keys   -> set<K>
// map<K,V>.Values -> list<V>
//
// list<T> .Len -> int
// map<K,V>.Len -> int
// set<T>  .Len -> int
// string  .Len -> int
//
// string.Substring(int, int) -> string
// string.Prefix(int)         -> string
// string.Suffix(int)         -> string
// string.ToUpper()           -> string
// string.ToLower()           -> string
// string.Trim()              -> string
// 
message FuncDecl {
  // Function unique ID.
  //
  // +Required
  string id = 1;

  // Function name.
  //
  // +Required
  string name = 2;

  // Type of the returned value.
  //
  // +Required
  TypeDef.FuncTypeDef func_type = 3;
}

// PrefixUnaryOpDecl models a prefix unary operation declaration.
message PrefixUnaryOpDecl {
  // Operation symbol. 
  //
  // +Required
  string op = 1;

  // Operation result type.
  //
  // +Required
  TypeDef result_type = 2;

  // Right hand side operand type.
  //
  // +Required
  TypeDef rhs_type = 3;
}

// PostfixUnaryOpDecl models a postfix unary operation declaration.
message PostfixUnaryOpDecl {
  // Operation symbol.
  //
  // +Required
  string op = 1;

  // Operation result type.
  //
  // +Required
  TypeDef result_type = 2;

  // Left hand side operand type.
  //
  // +Required
  TypeDef lhs_type = 3;
}

// BinaryOpDecl models a binary operation declaration.
message BinaryOpDecl {
  // Operation symbol.
  //
  // +Required
  string op = 1;

  // Operation result type.
  //
  // +Required
  TypeDef result_type = 2;

  // Left hand side operand type.
  //
  // +Required
  TypeDef lhs_type = 3;

  // Right hand side operand type.
  //
  // +Required
  TypeDef rhs_type = 4;
}

// ConstDef models a constant definition.
message ConstDef {
  // Constant name.
  //
  // +Required
  string name = 1;

  // Constant value.
  //
  // +Required
  Expr value = 3;
}

// FuncDef models a function definition.
message FuncDef {
  // Dependencies models what the function needs from the execution context.
  message Dependencies {

    // Functions called by the body.
    //
    // +Optional
    // +Constraints: $.all(IsPresent)
    repeated FuncDecl func_decls = 2;

    // Prefix unary operations used by the function.
    //
    // +Optional
    // +Constraints: $.all(IsPresent)
    repeated PrefixUnaryOpDecl prefix_unary_op_decls = 3;

    // Postfix unary operations used by the function.
    //
    // +Optional
    // +Constraints: $.all(IsPresent)
    repeated PostfixUnaryOpDecl postfix_unary_op_decls = 4;

    // Binary operations used by the function.
    //
    // +Optional
    // +Constraints: $.all(IsPresent)
    repeated BinaryOpDecl binary_op_decls = 5;
  }

  // Function declaration.
  //
  // +Required
  FuncDecl decl = 1;

  // Function body.
  //
  // +Required
  Expr body = 2;

  // Function dependencies on the execution context.
  //
  // +Optional
  Dependencies dependencies = 3;
}

// Package models a GEL package - a set of GEL definitions.
//
// +Constraints: $var_decls.len + $func_defs.len > 0
//   >> package does not define constants nor functions.
message Package {
  // Package name.
  //
  // +Required
  string name = 1;

  // Constants defined by the package. 
  //
  // +Optional
  // +Constraints: $.all(IsPresent)
  repeated ConstDef const_defs = 2;

  // Functions defined by the package.
  //
  // +Optional
  // +Constraints: $.all(IsPresent)
  repeated FuncDef func_defs = 3;
}
